# Generated by Django 5.2.1 on 2025-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='days',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
