# Generated by Django 5.2.1 on 2025-06-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_taxibooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
