# Generated by Django 5.2.1 on 2025-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_booking_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='video',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
