# Generated by Django 5.2.1 on 2025-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_booking_video_tourpackage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(upload_to='packages/images/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='packages/videos/'),
        ),
    ]
